[2023-03-30T15:34:04.207+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: citi_bikes_nyc.unzip_data manual__2023-03-30T15:33:31.037725+00:00 [queued]>
[2023-03-30T15:34:04.215+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: citi_bikes_nyc.unzip_data manual__2023-03-30T15:33:31.037725+00:00 [queued]>
[2023-03-30T15:34:04.216+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-03-30T15:34:04.216+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2023-03-30T15:34:04.216+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-03-30T15:34:04.228+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): unzip_data> on 2023-03-30 15:33:31.037725+00:00
[2023-03-30T15:34:04.234+0000] {standard_task_runner.py:55} INFO - Started process 8692 to run task
[2023-03-30T15:34:04.236+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'citi_bikes_nyc', 'unzip_data', 'manual__2023-03-30T15:33:31.037725+00:00', '--job-id', '263', '--raw', '--subdir', 'DAGS_FOLDER/citi_bikes_nyc.py', '--cfg-path', '/tmp/tmpnfw1f8en']
[2023-03-30T15:34:04.238+0000] {standard_task_runner.py:83} INFO - Job 263: Subtask unzip_data
[2023-03-30T15:34:04.285+0000] {task_command.py:389} INFO - Running <TaskInstance: citi_bikes_nyc.unzip_data manual__2023-03-30T15:33:31.037725+00:00 [running]> on host ea14cce7ead9
[2023-03-30T15:34:04.339+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=citi_bikes_nyc
AIRFLOW_CTX_TASK_ID=unzip_data
AIRFLOW_CTX_EXECUTION_DATE=2023-03-30T15:33:31.037725+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-30T15:33:31.037725+00:00
[2023-03-30T15:34:04.340+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-03-30T15:34:04.341+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'gunzip /opt/***/dags/data/202201-citibike-tripdata.csv.zip -d /opt/***/dags/data']
[2023-03-30T15:34:04.351+0000] {subprocess.py:86} INFO - Output:
[2023-03-30T15:34:04.354+0000] {subprocess.py:93} INFO - gzip: /opt/***/dags/data/202201-citibike-tripdata.csv.zip: unknown suffix -- ignored
[2023-03-30T15:34:04.354+0000] {subprocess.py:93} INFO - gzip: /opt/***/dags/data is a directory -- ignored
[2023-03-30T15:34:04.354+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-03-30T15:34:04.363+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-03-30T15:34:04.365+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=citi_bikes_nyc, task_id=unzip_data, execution_date=20230330T153331, start_date=20230330T153404, end_date=20230330T153404
[2023-03-30T15:34:04.374+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 263 for task unzip_data (Bash command failed. The command returned a non-zero exit code 2.; 8692)
[2023-03-30T15:34:04.407+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-03-30T15:34:04.426+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
