[2023-03-30T15:32:39.463+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: citi_bikes_nyc.unzip_data manual__2023-03-30T15:29:26.735509+00:00 [queued]>
[2023-03-30T15:32:39.472+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: citi_bikes_nyc.unzip_data manual__2023-03-30T15:29:26.735509+00:00 [queued]>
[2023-03-30T15:32:39.472+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-03-30T15:32:39.473+0000] {taskinstance.py:1284} INFO - Starting attempt 2 of 3
[2023-03-30T15:32:39.473+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-03-30T15:32:39.487+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): unzip_data> on 2023-03-30 15:29:26.735509+00:00
[2023-03-30T15:32:39.494+0000] {standard_task_runner.py:55} INFO - Started process 8536 to run task
[2023-03-30T15:32:39.496+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'citi_bikes_nyc', 'unzip_data', 'manual__2023-03-30T15:29:26.735509+00:00', '--job-id', '259', '--raw', '--subdir', 'DAGS_FOLDER/citi_bikes_nyc.py', '--cfg-path', '/tmp/tmp0kaej3jg']
[2023-03-30T15:32:39.498+0000] {standard_task_runner.py:83} INFO - Job 259: Subtask unzip_data
[2023-03-30T15:32:39.552+0000] {task_command.py:389} INFO - Running <TaskInstance: citi_bikes_nyc.unzip_data manual__2023-03-30T15:29:26.735509+00:00 [running]> on host ea14cce7ead9
[2023-03-30T15:32:39.611+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=citi_bikes_nyc
AIRFLOW_CTX_TASK_ID=unzip_data
AIRFLOW_CTX_EXECUTION_DATE=2023-03-30T15:29:26.735509+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-30T15:29:26.735509+00:00
[2023-03-30T15:32:39.612+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-03-30T15:32:39.613+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'gunzip /opt/***/dags/data/202201-citibike-tripdata.csv.zip -d /opt/***/dags/data']
[2023-03-30T15:32:39.623+0000] {subprocess.py:86} INFO - Output:
[2023-03-30T15:32:39.626+0000] {subprocess.py:93} INFO - gzip: /opt/***/dags/data/202201-citibike-tripdata.csv.zip: unknown suffix -- ignored
[2023-03-30T15:32:39.627+0000] {subprocess.py:93} INFO - gzip: /opt/***/dags/data is a directory -- ignored
[2023-03-30T15:32:39.627+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-03-30T15:32:39.636+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-03-30T15:32:39.639+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=citi_bikes_nyc, task_id=unzip_data, execution_date=20230330T152926, start_date=20230330T153239, end_date=20230330T153239
[2023-03-30T15:32:39.649+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 259 for task unzip_data (Bash command failed. The command returned a non-zero exit code 2.; 8536)
[2023-03-30T15:32:39.668+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-03-30T15:32:39.692+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
